name: Validate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    uses: ronin-co/github-actions/.github/workflows/validate.yml@main
    with:
      package_dir: './'  # Adjust if your package is in a subdirectory